import 'package:flutter/material.dart';

List<Map<String, dynamic>> jobs = [
  {
    'position': 'Freelance Mobile App Developer',
    'employer': 'Toptal',
    'location': 'Nigeria',
    'physical_or_remote': 'Remote',
    'time_since_post': '2 hours ago',
    'company_logo': 'images/Ainz oool gown.jpg',
  },
  {
    'position': 'Web Developer',
    'employer': 'Yoodule',
    'location': 'Nigeria',
    'physical_or_remote': 'Remote',
    'time_since_post': '1 day ago',
    'company_logo': 'images/godzilla_pic.jpg',
  },
  {
    'position': 'No-Code Developer for Bubble.io',
    'employer': 'Beer Tree Brew',
    'location': 'Nigeria',
    'physical_or_remote': 'Remote',
    'time_since_post': '1 minute ago',
    'company_logo': 'images/megamind.jpeg',
  },
  {
    'position': 'Freelance Mobile App Developer',
    'employer': 'Toptal',
    'location': 'Nigeria',
    'physical_or_remote': 'Remote',
    'time_since_post': '2 hours ago',
    'company_logo': 'images/Ainz oool gown.jpg',
  },
  {
    'position': 'Web Developer',
    'employer': 'Yoodule',
    'location': 'Nigeria',
    'physical_or_remote': 'Remote',
    'time_since_post': '1 day ago',
    'company_logo': 'images/godzilla_pic.jpg',
  },
  {
    'position': 'No-Code Developer for Bubble.io',
    'employer': 'Beer Tree Brew',
    'location': 'Nigeria',
    'physical_or_remote': 'Remote',
    'time_since_post': '1 minute ago',
    'company_logo': 'images/megamind.jpeg',
  },
  {
    'position': 'Freelance Mobile App Developer',
    'employer': 'Toptal',
    'location': 'Nigeria',
    'physical_or_remote': 'Remote',
    'time_since_post': '2 hours ago',
    'company_logo': 'images/Ainz oool gown.jpg',
  },
];